#pragma once



#if defined(ARDUINO_ARCH_AVR)
	#define QYBERCOM_PROTONIX_ANALOG_MAX 1023
#elif defined(ARDUINO_ARCH_SAMD)
	#define QYBERCOM_PROTONIX_ANALOG_MAX 1023
#elif defined(ARDUINO_ARCH_SAM)
	#define QYBERCOM_PROTONIX_ANALOG_MAX 4095
#elif defined(ARDUINO_ARCH_STM32)
	#define QYBERCOM_PROTONIX_ANALOG_MAX 4095
#elif defined(ESP8266)
	#define QYBERCOM_PROTONIX_ANALOG_MAX 1023
#elif defined(ESP32)
	#define QYBERCOM_PROTONIX_ANALOG_MAX 4095
#else
	#define QYBERCOM_PROTONIX_ANALOG_MAX 1023
#endif


#if defined(LED_BUILTIN)
	#define QYBERCOM_PROTONIX_LED_PIN LED_BUILTIN
	#define QYBERCOM_PROTONIX_LED_ON HIGH
	#define QYBERCOM_PROTONIX_LED_OFF LOW
#else
	#if defined(ESP8266)
		#define QYBERCOM_PROTONIX_LED_PIN 2
		#define QYBERCOM_PROTONIX_LED_ON LOW
		#define QYBERCOM_PROTONIX_LED_OFF HIGH
	#endif
	#if defined(ESP32)
		#define QYBERCOM_PROTONIX_LED_PIN 2
		#define QYBERCOM_PROTONIX_LED_ON HIGH
		#define QYBERCOM_PROTONIX_LED_OFF LOW
	#endif
#endif

#if defined(ESP32) || defined(ESP8266)
#define QYBERCOM_PROTONIX_INTERRUPT IRAM_ATTR
#else
#define QYBERCOM_PROTONIX_INTERRUPT
#endif

#if defined(AVR)
#define QYBERCOM_PROTONIX_MEMORY_EEPROM_SIZE 1024
#define QYBERCOM_PROTONIX_REGISTRY_START 0
#endif

#if defined(ESP8266)
#define QYBERCOM_PROTONIX_MEMORY_EEPROM_SIZE 512
#define QYBERCOM_PROTONIX_REGISTRY_START 0
#endif

#if defined(ESP32)
#define QYBERCOM_PROTONIX_MEMORY_EEPROM_SIZE 4096
#define QYBERCOM_PROTONIX_REGISTRY_START 0
#endif